main: atomiccraft.com.br.MuMagnata
name: MuMagnata
version: 1.0.3
author: Mushu949

commands:
    magnata:
        description: ver o magnata atual.
        aliases: [mag, maisrico, baltop]
        usage: Use /magnata