main: atomiccraft.com.br.Main
name: MuMagnata
version: 1.0.1
author: Mushu949

commands:
    magnata:
        description: ver o magnata atual.
        aliases: [mag, maisrico]
        usage: Use /magnata